# Generated by Django 5.0.2 on 2024-03-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='uploads/images')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(default='all', max_length=30)),
                ('ratings', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feature', models.BooleanField(default=False)),
            ],
        ),
    ]
