# Generated by Django 5.0.2 on 2024-03-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
