# Generated by Django 5.0.2 on 2024-03-07 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
