# Generated by Django 5.0.2 on 2024-04-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
